blank_issues_enabled: false
contact_links:
  - name: Yuricord Support Server
    url: https://discord.gg/D9uwnFnqmd
    about: If you need help regarding Yuricord, please join our support server!
  - name: Yuricord Installer
    url: https://github.com/Yuricord/Installer
    about: You can find the Yuricord Installer here


